### ISSUE TITLE
[Feat] Slack & AI 서비스 프로젝트 설정 및 엔티티 생성

### ISSUE THREAD

**Issue by CJ-1998** [MSA-Logistics-service/backend#15]
### TODO
---
- [X] build.gradle 수정
- [X] application.yml 작성
- [X] 공통 로직 추가
- [X] Slack 엔티티 개발
- [X] AI 엔티티 개발
