### ISSUE TITLE
[Feat] 상품 도메인 ai 채팅 기능 구현

### ISSUE THREAD

**Issue by kyungjinleelee** [MSA-Logistics-service/backend#40]
## TODO
- [x] 엔티티 파일 작성
- [x] API 키 발급
- [x] RestTemplate 연동
- [x] 컨트롤러, 서비스, 레포 파일 작성
- [x] 인증/인가 리팩토링
