### ISSUE TITLE
[Feat] AI 및 Slack 서비스 구현

### ISSUE THREAD

**Issue by CJ-1998** [MSA-Logistics-service/backend#52]
### TODO
---
- [ ] AI 관련 CRUD 구현
- [ ] Slack 관련 CR 구현
- [ ] Slack 메시지 발송 로직 구현
